---
essentials:
  packages:
    - rsync
    - lynx
    - bash
    - curl
    - wget
    - git
    - acl
    - ntp
    - zip
    - unzip
    - python3-pip
    - imagemagick
    - apt-transport-https
    - default-jre-headless
    - stunnel4
    - nfs-common
  remove_packages:
    - python2*
  ssl_certs:
    - name: app
      path: /etc/ssl
      bits: 2048
      type: rsa
      days: 3650
      CommonName: "*"
  users:
    - name: ubuntu
      group: ubuntu
      ssh:
        config:
          - Host: github.com
            StrictHostKeyChecking: "no"
  hosts:
    127.0.0.1: app web db search

webapp:
  release_dir: ""
  installation_path: "/home/{{ ansible_user_id }}"
  apps:
    - name: app
      directories:
        - /mnt/app/s3
        - /mnt/app/s3fs

mysql:
  users:
    - name: app
      password: app
      priv: "app.*:ALL,GRANT/`app\\_%`.*:ALL,GRANT"
      host: "localhost"
  databases:
    - name: "app"
  cnf:
    mysqld:
      sort_buffer_size : 32M
      query_cache_type: 1
      query_cache_limit: 10M
      query_cache_size: 128M
      max_allowed_packet: 32M
      tmp_table_size: 64M
      bulk_insert_buffer_size: 16M
      query_cache_min_res_unit: 8192
      query_alloc_block_size: 16384
      query_prealloc_size: 16384
      transaction_prealloc_size: 1048576
      transaction_alloc_block_size: 2097152
      innodb_buffer_pool_size: 512M
      innodb_log_buffer_size: 8M
      innodb_table_locks: 0
      innodb_rollback_on_timeout: 1

php:
  modules:
    - cli
    - mbstring
    - curl
    - soap
    - xsl
    - intl
    - mysql
    - imagick
    - gd
    - mcrypt
    - ldap
    - zip
  packages:
    - libapache2-mod-php5.6
  ini:
    ALL:
      expose_php: 'Off'
      variables_order: 'EGPCS'
      realpath_cache_size: 8192K
      realpath_cache_ttl: 3600
      Date:
       timezone: 'America/New_York'
      opcache:
        max_accelerated_files: 30000
        memory_consumption: 512
        enable_file_override: 1
        interned_strings_buffer: 16
        revalidate_path: 1
        revalidate_freq: 0
    apache2:
      post_max_size: '120M'
      upload_max_filesize: '120M'
      memory_limit: '512M'
      max_execution_time: '120'

apache:
  config:
    Options: "FollowSymLinks"
    ServerTokens: "Prod"
    ServerSignature: "Off"
  sections:
    Directory:
      - "/":
        - "Options +FollowSymLinks -Indexes -Includes -ExecCGI"
        - "AllowOverride None"
        - "Order Deny,Allow"
        - "Deny from all"
        - "Require all denied"
  ssl:
    SSLProtocol: "all -SSLv2 -SSLv3 -TLSv1"
    SSLCipherSuite: "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
  enable_modules:
    - ssl
    - rewrite
    - expires
    - headers
  virtualhosts:
    - listen: "*:80"
      directives:
        core:
          ServerName: app
          ServerAlias:
            - "*"
          DocumentRoot: "/home/{{ ansible_user_id }}/app"
        ssl:
          SSLCertificateFile: /etc/ssl/app.crt
          SSLCertificateKeyFile: /etc/ssl/app.key

s3fs:
  buckets:
    - mountpoint: /mnt/app/s3fs
      bucket: s3fs-storage
      options: "allow_other,use_cache=/tmp,max_stat_cache_size='100000',uid=33,gid=33,umask=002"
  source: "https://github.com/mauricios/s3fs-fuse/archive/master.zip"
  add_to_fstab: False

cleanbox:
  remove:
    - "/tmp/s3fs-fuse-*"
    - "~/s3fs-fuse-*"
